# Generated by Django 5.0.6 on 2024-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0002_remove_leaderboard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
