# Generated by Django 5.0.6 on 2024-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0003_questions_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
