# Generated by Django 5.0.6 on 2024-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0004_alter_questions_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
