# Generated by Django 5.0.6 on 2024-06-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizgame', '0008_googlecredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleCredential',
        ),
    ]
